CREATE TABLE IF NOT EXISTS cus_customer(
    cus_id      BIGINT PRIMARY KEY,
    cus_balance DECIMAL(38),
    cus_limit   DECIMAL(38)
);

CREATE TABLE IF NOT EXISTS tra_transaction(
    tra_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tra_customer_id BIGINT,
    tra_value       DECIMAL(38),
    tra_type        CHAR(1),
    tra_description VARCHAR(10),
    tra_created_at  TIMESTAMP,
    FOREIGN KEY (tra_customer_id) REFERENCES cus_customer (cus_id)
);

insert into cus_customer VALUES (1, 0, 100000);
insert into cus_customer VALUES (2, 0, 80000);
insert into cus_customer VALUES (3, 0, 1000000);
insert into cus_customer VALUES (4, 0, 10000000);
insert into cus_customer VALUES (5, 0, 500000);