FROM golang:1.21.6-alpine as builder

RUN apk add --no-cache gcc musl-dev

WORKDIR /app

COPY loadBalancer /app

RUN go build -o shinsei

FROM alpine:latest

COPY --from=builder /app/shinsei /app/shinsei

WORKDIR /app

EXPOSE 9999

CMD ["./shinsei"]

