# syntax=docker/dockerfile:1
FROM python:latest
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /code
COPY requirements.txt /code/
RUN pip install --no-cache-dir --upgrade -r requirements.txt
COPY . /code/
WORKDIR /code/
CMD uvicorn app.main:app --host 0.0.0.0 --port 3000 --timeout-keep-alive 300
