###

GET http://localhost:9999/clientes/1/extrato

### 
GET http://172.29.0.3:8080/clientes/7/extrato

###
POST  http://localhost:9999/clientes/1/transacoes
content-type: application/json

{
    "valor": 1,  
    "tipo" : "d",
    "descricao" : "c"
}