CREATE UNLOGGED TABLE IF NOT EXISTS public.cliente
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    limite integer NOT NULL,
    saldo integer NOT NULL,
    versao integer NOT NULL default 1,
    CONSTRAINT cliente_pkey PRIMARY KEY (id),
    CONSTRAINT saldo_limite_check CHECK (saldo >= (- limite))
);

CREATE UNLOGGED TABLE IF NOT EXISTS public.transacao
(
    id_cliente bigint NOT NULL,
    valor integer NOT NULL,
    realizada_em timestamp without time zone NOT NULL DEFAULT now(),
    tipo character varying(1) COLLATE pg_catalog."default" NOT NULL,
    descricao character varying(10) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT transacao_cliente_id_idx FOREIGN KEY (id_cliente)
        REFERENCES public.cliente (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE INDEX IF NOT EXISTS id_cliente_idx
    ON public.transacao USING btree
        (id_cliente ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS realizada_em_idx
    ON public.transacao USING btree
        (realizada_em ASC NULLS LAST)
    TABLESPACE pg_default;

insert into cliente (id, limite, saldo) values (1, 100000, 0);
insert into cliente (id, limite, saldo) values (2, 80000, 0);
insert into cliente (id, limite, saldo) values (3, 1000000, 0);
insert into cliente (id, limite, saldo) values (4, 10000000, 0);
insert into cliente (id, limite, saldo) values (5, 500000, 0);
