CREATE UNLOGGED TABLE IF NOT EXISTS clientes (
  "id" INTEGER PRIMARY KEY NOT NULL,
  "saldo" INTEGER NOT NULL,
  "limite" INTEGER NOT NULL,
  "ultimas_transacoes" JSONB NOT NULL DEFAULT '[]'::JSONB
);
DELETE FROM clientes;
INSERT INTO clientes VALUES(1,0,100000,'[]');
INSERT INTO clientes VALUES(2,0,80000,'[]');
INSERT INTO clientes VALUES(3,0,1000000,'[]');
INSERT INTO clientes VALUES(4,0,10000000,'[]');
INSERT INTO clientes VALUES(5,0,500000,'[]');
