CREATE TABLE public.customers (
	id smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 100 START 1 CACHE 1 NO CYCLE),
	balance int NOT NULL,
	"limit" int NOT NULL,
	"version" int NOT NULL,
	"created_at" timestamptz NOT NULL,
	"update_at" timestamptz NULL,
	CONSTRAINT "uq_customers_id" PRIMARY KEY (id)
);

CREATE TABLE public.transactions (
	id int NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 10000000 START 1 CACHE 1 NO CYCLE),
	"amount" int NOT NULL,
	"description" varchar(10) NOT NULL,
	"type" smallint NOT NULL, 
	"created_at" timestamptz NOT NULL,
	"customer_id" smallint NOT NULL,
	CONSTRAINT fk_transactions_customer_id FOREIGN KEY (customer_id) REFERENCES public.customers(id),
	CONSTRAINT "uq_transactions_id" PRIMARY KEY (id)
);


INSERT INTO public.customers (balance, "limit", "version", "created_at", "update_at")
VALUES (0, 100000, 0, CURRENT_TIMESTAMP, NULL);

INSERT INTO public.customers (balance, "limit", "version", "created_at", "update_at")
VALUES (0, 80000, 0, CURRENT_TIMESTAMP, NULL);

INSERT INTO public.customers (balance, "limit", "version", "created_at", "update_at")
VALUES (0, 1000000, 0, CURRENT_TIMESTAMP, NULL);

INSERT INTO public.customers (balance, "limit", "version", "created_at", "update_at")
VALUES (0, 10000000, 0, CURRENT_TIMESTAMP, NULL);

INSERT INTO public.customers (balance, "limit", "version", "created_at", "update_at")
VALUES (0, 500000, 0, CURRENT_TIMESTAMP, NULL);