# Generated by Django 5.0.2 on 2024-02-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('limite', models.IntegerField()),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Saldos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField()),
            ],
            options={
                'db_table': 'saldos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transacoes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField()),
                ('tipo', models.CharField(choices=[('C', 'Crédito'), ('D', 'Débito')], max_length=1)),
                ('descricao', models.CharField(max_length=10)),
                ('realizada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'transacoes',
                'managed': False,
            },
        ),
    ]
