CREATE USER postgres SUPERUSER;

CREATE TABLE IF NOT EXISTS "clients" (
  "id" SERIAL PRIMARY KEY,
  "balance" INTEGER NOT NULL DEFAULT 0, 
  "limit" INTEGER NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "transactions" (
	"id" SERIAL PRIMARY KEY,
	"client_id" INTEGER NOT NULL,
	"type" VARCHAR(1) NOT NULL,
	"amount" INTEGER NOT NULL,
	"description" VARCHAR(10) NOT NULL,
	"created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);