requires 'HTTP::Server::Simple', '0.52';
requires 'CGI', '4.61';
requires 'HTTP::Server::Simple::CGI::PreFork', '6.00';
requires 'JSON', '4.10';
requires 'DateTime', '1.65';
requires 'DateTimeX::TO_JSON', '0.0.2';
requires 'Tie::RegexpHash', '0.17';
requires 'DBI', '1.643';
requires 'DBD::SQLite', '1.74';
requires 'DateTime::Format::RFC3339';
requires 'Slick', '0.007';
